name: Build and Push to Dockerhub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t nerojz/react-test -f ./client/Dockerfile.dev ./client

      - name: Run Test
        run: docker run -e CI=true nerojz/react-test npm test

      - name: Build Prod Images
        steps:
          - run: docker build -t nerojz/multi-client ./client
          - run: docker build -t nerojz/multi-worker ./worker
          - run: docker build -t nerojz/multi-server ./server
          - run: docker build -t nerojz/multi-nginx ./nginx
